#!/bin/bash

# GitHub Repository Setup Script for Pelosi Trade Tracker
echo "🚀 GitHub Repository Setup for Pelosi Trade Tracker"
echo "=================================================="
echo ""

# Get current directory name for repository name
REPO_NAME="pelosi-trade-tracker"
echo "📁 Suggested repository name: $REPO_NAME"
echo ""

echo "📋 Next Steps:"
echo "=============="
echo ""
echo "1. 🌐 Go to GitHub.com and sign in"
echo "2. ➕ Click the '+' button → 'New repository'"
echo "3. 📝 Repository details:"
echo "   - Name: $REPO_NAME"
echo "   - Description: Automated tracker for Nancy Pelosi's financial disclosures with Discord notifications"
echo "   - Visibility: Public (recommended) or Private"
echo "   - ❌ DON'T initialize with README (we already have one)"
echo "   - ❌ DON'T add .gitignore (we already have one)"
echo "   - ❌ DON'T add license (optional)"
echo ""
echo "4. ✅ Click 'Create repository'"
echo ""
echo "5. 📋 Copy the repository URL (it will look like):"
echo "   https://github.com/MajesticBison/$REPO_NAME.git"
echo ""
echo "6. 🔗 Add the remote and push:"
echo "   git remote add origin https://github.com/MajesticBison/$REPO_NAME.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "🎯 Repository Features:"
echo "======================"
echo "✅ Complete Pelosi trade tracking system"
echo "✅ Cross-platform support (macOS + Windows)"
echo "✅ Discord integration with rich embeds"
echo "✅ Automated scheduling (cron/Task Scheduler)"
echo "✅ Comprehensive documentation"
echo "✅ Easy setup scripts"
echo "✅ Rate limiting and error handling"
echo ""

echo "📊 What's Included:"
echo "==================="
echo "• Main tracking script (pelosi_tracker.py)"
echo "• Web scraper for House Clerk site"
echo "• PDF parser for trade extraction"
echo "• Discord notifier with color-coded alerts"
echo "• SQLite database for duplicate prevention"
echo "• Setup scripts for both platforms"
echo "• Detailed documentation and deployment guides"
echo "• Status monitoring tools"
echo ""

echo "🔧 After pushing to GitHub:"
echo "==========================="
echo "• Share the repository URL with others"
echo "• Clone on other machines: git clone <repo-url>"
echo "• Create issues for bug reports or feature requests"
echo "• Use GitHub Actions for CI/CD (optional)"
echo "• Add topics/tags: python, discord, web-scraping, financial-disclosures"
echo ""

echo "💡 Pro Tips:"
echo "============"
echo "• Add a LICENSE file (MIT recommended)"
echo "• Create a CONTRIBUTING.md for contributors"
echo "• Add GitHub Actions for automated testing"
echo "• Use GitHub Releases for version management"
echo "• Consider adding a demo GIF to the README"
echo ""

echo "Ready to create the repository? Follow the steps above! 🚀"
